server:
  port: 7788
spring:
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  application:
    name: user-story-mapping-web
  data:
    mongodb:
      uri: mongodb://47.99.138.113:27017/usm_db
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
spring.jackson.serialization.WRITE_DATES_AS_TIMESTAMPS: true  #返回JSON统一日期为时间戳
spring.jackson.serialization.WRITE_DATE_TIMESTAMPS_AS_NANOSECONDS: false
project:
  groupId: @project.groupId@
  artifactId: @project.artifactId@
  version: @project.version@
  name: @project.name@
  description: @project.description@
  url: @project.url@